services:
  - type: web
    name: kufe-article-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
